// constants/foodNames.ts
// A prefix-search list of common food NAMES. No nutrition here — that still
// comes from USDA.
//
// WHY THIS EXISTS. Both nutrition APIs match WHOLE WORDS. Typing "broc"
// returns nothing from either of them, because "broc" isn't a word in
// "Broccoli, raw" — you have to spell the whole thing before anything appears.
// That's a miserable way to search, and it reads as the app being broken
// rather than the database being strict.
//
// So this list sits in front: "broc" matches "broccoli" HERE, instantly and
// offline, and the full word is what gets sent to the API. The user types
// three letters; the network sees a word it can actually match.
//
// CURATED, not scraped. A list of every food in existence would make the
// prefix match noisier than no match at all — twenty thousand entries means
// "chi" returns four hundred things nobody was looking for. These are the
// foods people actually log, including West African dishes that most
// nutrition apps ignore entirely.
//
// Anything NOT in this list still works — it just needs the full word, which
// is exactly how the search behaved before this file existed. Adding a name
// here can only ever help.

export const FOOD_NAMES: string[] = [
  "aioli",
  "akara",
  "alfredo sauce",
  "almond butter",
  "almond milk",
  "almonds",
  "amala",
  "americano",
  "anchovies",
  "apple",
  "apple juice",
  "apple pie",
  "apricot",
  "arepa",
  "artichoke",
  "arugula",
  "asparagus",
  "aubergine",
  "avocado",
  "avocado oil",
  "bacon",
  "bagel",
  "baguette",
  "baked beans",
  "balsamic vinegar",
  "banana",
  "barbecue sauce",
  "barley",
  "basmati rice",
  "beef curry",
  "beef mince",
  "beef steak",
  "beef stew",
  "beer",
  "beet",
  "beetroot",
  "bell pepper",
  "biscuit",
  "black beans",
  "black coffee",
  "black eyed peas",
  "black pepper",
  "black tea",
  "blackberries",
  "blue cheese",
  "blueberries",
  "blueberry muffin",
  "boiled egg",
  "bok choy",
  "brazil nuts",
  "bread",
  "brie",
  "brisket",
  "broccoli",
  "brown rice",
  "brown sugar",
  "brownie",
  "brussels sprouts",
  "buckwheat",
  "bulgur",
  "bun",
  "burger",
  "burrito",
  "burrito bowl",
  "butter",
  "butter chicken",
  "butternut squash",
  "cabbage",
  "caesar dressing",
  "caesar salad",
  "cake",
  "calamari",
  "candy",
  "canned tuna",
  "cantaloupe",
  "cappuccino",
  "carrot",
  "carrot cake",
  "carrots",
  "cashews",
  "casserole",
  "catfish",
  "cauliflower",
  "celery",
  "cereal",
  "cereal bar",
  "chai",
  "champagne",
  "chapman",
  "cheddar cheese",
  "cheese",
  "cheese pizza",
  "cheeseburger",
  "cheesecake",
  "cherries",
  "cherry tomatoes",
  "chia seeds",
  "chicken breast",
  "chicken curry",
  "chicken drumstick",
  "chicken soup",
  "chicken thigh",
  "chicken wings",
  "chickpeas",
  "chili",
  "chili pepper",
  "chimichurri",
  "chin chin",
  "chips",
  "chocolate",
  "chocolate bar",
  "chocolate cake",
  "chocolate chip cookie",
  "chorizo",
  "chow mein",
  "clementine",
  "club sandwich",
  "cocktail",
  "coconut",
  "coconut milk",
  "coconut oil",
  "coconut water",
  "cod",
  "coffee",
  "coke",
  "cola",
  "coleslaw",
  "condensed milk",
  "cookies",
  "corn",
  "cornflakes",
  "cottage cheese",
  "courgette",
  "couscous",
  "couscous salad",
  "crab",
  "crackers",
  "cranberries",
  "cranberry juice",
  "cream",
  "cream cheese",
  "creme fraiche",
  "croissant",
  "cucumber",
  "cupcake",
  "curry",
  "curry paste",
  "custard",
  "danish",
  "dark chocolate",
  "dates",
  "donut",
  "doughnut",
  "dried apricots",
  "duck",
  "dumpling",
  "dumplings",
  "eba",
  "edamame",
  "egg",
  "egg sandwich",
  "egg white",
  "eggplant",
  "eggs",
  "egusi soup",
  "enchilada",
  "energy bar",
  "energy drink",
  "english muffin",
  "espresso",
  "evaporated milk",
  "falafel",
  "farro",
  "feta cheese",
  "figs",
  "fish and chips",
  "fish cake",
  "fish sauce",
  "flat white",
  "flatbread",
  "flax seeds",
  "french fries",
  "french toast",
  "fried chicken",
  "fried egg",
  "fried rice",
  "fufu",
  "garlic",
  "garri",
  "ghee",
  "gin",
  "ginger",
  "gnocchi",
  "goat cheese",
  "goat meat",
  "granola",
  "granola bar",
  "grape juice",
  "grapefruit",
  "grapes",
  "gravy",
  "greek salad",
  "greek yogurt",
  "green apple",
  "green beans",
  "green lentils",
  "green onion",
  "green pepper",
  "green tea",
  "grilled chicken",
  "grits",
  "ground beef",
  "ground lamb",
  "ground pork",
  "ground turkey",
  "guacamole",
  "guava",
  "gummy bears",
  "gyro",
  "haddock",
  "halloumi",
  "ham",
  "hamburger",
  "harissa",
  "hash browns",
  "hazelnuts",
  "heavy cream",
  "hemp seeds",
  "herbal tea",
  "honey",
  "honeydew melon",
  "hot chocolate",
  "hot dog",
  "hot sauce",
  "hummus",
  "ice cream",
  "iced coffee",
  "injera",
  "instant noodles",
  "jalapeno",
  "jam",
  "jasmine rice",
  "jelly",
  "jollof rice",
  "kale",
  "kebab",
  "kefir",
  "ketchup",
  "kidney beans",
  "kiwi",
  "kombucha",
  "lamb chop",
  "lard",
  "lasagna",
  "latte",
  "leek",
  "lemon",
  "lemonade",
  "lentil soup",
  "lentils",
  "lettuce",
  "lime",
  "liver",
  "lobster",
  "lychee",
  "mac and cheese",
  "macadamia nuts",
  "macaroni",
  "mackerel",
  "mandarin",
  "mango",
  "maple syrup",
  "margarine",
  "marinara sauce",
  "marshmallow",
  "mashed potato",
  "matcha",
  "mayonnaise",
  "meatballs",
  "meatloaf",
  "milk",
  "milk chocolate",
  "milkshake",
  "millet",
  "miso soup",
  "mocha",
  "moin moin",
  "mozzarella",
  "muesli",
  "muffin",
  "mushroom",
  "mushrooms",
  "mussels",
  "mustard",
  "naan",
  "nachos",
  "navy beans",
  "nectarine",
  "noodles",
  "nutella",
  "oat milk",
  "oatmeal",
  "oats",
  "octopus",
  "okra",
  "olive oil",
  "olives",
  "omelette",
  "onion",
  "orange",
  "orange juice",
  "oyster sauce",
  "pad thai",
  "palm oil",
  "palm wine",
  "pancakes",
  "papaya",
  "parmesan",
  "parsnip",
  "passion fruit",
  "pasta",
  "pastry",
  "peach",
  "peanut butter",
  "peanuts",
  "pear",
  "peas",
  "pecans",
  "penne",
  "pepper soup",
  "pepperoni",
  "pepperoni pizza",
  "pesto",
  "pho",
  "pie",
  "pineapple",
  "pinto beans",
  "pistachios",
  "pita bread",
  "pizza",
  "plantain",
  "plum",
  "poke bowl",
  "polenta",
  "pomegranate",
  "popcorn",
  "pork belly",
  "pork chop",
  "porridge",
  "portobello mushroom",
  "pot roast",
  "potato",
  "potato chips",
  "potato salad",
  "pounded yam",
  "prawns",
  "pretzel",
  "protein bar",
  "protein powder",
  "protein shake",
  "prunes",
  "puff puff",
  "pumpkin",
  "pumpkin seeds",
  "quesadilla",
  "quinoa",
  "radish",
  "raisins",
  "ramen",
  "ranch dressing",
  "raspberries",
  "ravioli",
  "red cabbage",
  "red grapes",
  "red lentils",
  "red onion",
  "red pepper",
  "red wine",
  "refried beans",
  "ribeye steak",
  "rice cakes",
  "rice noodles",
  "rice pudding",
  "ricotta",
  "risotto",
  "roast beef",
  "roast chicken",
  "roast potatoes",
  "roll",
  "romaine lettuce",
  "rum",
  "rye bread",
  "salad",
  "salad dressing",
  "salami",
  "salmon",
  "salsa",
  "salt",
  "samosa",
  "sandwich",
  "sardines",
  "sashimi",
  "sausage",
  "scallops",
  "scone",
  "scrambled eggs",
  "sea bass",
  "seaweed",
  "seitan",
  "semolina",
  "sesame oil",
  "sesame seeds",
  "shawarma",
  "shepherds pie",
  "shrimp",
  "sirloin steak",
  "skim milk",
  "skyr",
  "smoked salmon",
  "smoothie",
  "soba",
  "soda",
  "soup",
  "sour cream",
  "sourdough bread",
  "soy milk",
  "soy sauce",
  "soybeans",
  "spaghetti",
  "sparkling water",
  "spinach",
  "split peas",
  "sports drink",
  "spring onion",
  "spring roll",
  "sprite",
  "squid",
  "sriracha",
  "stew",
  "stir fry",
  "strawberries",
  "sugar",
  "sunflower oil",
  "sunflower seeds",
  "sushi",
  "suya",
  "sweet corn",
  "sweet potato",
  "swiss chard",
  "swiss cheese",
  "syrup",
  "taco",
  "tahini",
  "tea",
  "tempeh",
  "teriyaki sauce",
  "tikka masala",
  "tilapia",
  "tofu",
  "tomato",
  "tomato sauce",
  "tomato soup",
  "tortilla",
  "tortilla chips",
  "trail mix",
  "trout",
  "tuna",
  "turkey breast",
  "turnip",
  "tuwo",
  "tzatziki",
  "udon",
  "vegetable oil",
  "vegetable soup",
  "vinaigrette",
  "vinegar",
  "vodka",
  "waffles",
  "walnuts",
  "water",
  "watercress",
  "watermelon",
  "whey protein",
  "whiskey",
  "white beans",
  "white bread",
  "white rice",
  "white wine",
  "whole milk",
  "whole wheat bread",
  "wild rice",
  "wine",
  "worcestershire sauce",
  "wrap",
  "yam",
  "yogurt",
  "zobo",
  "zucchini",
];

/** Names starting with what's been typed so far.
    Prefix, not substring: "rice" should suggest "rice noodles", not every
    food with "rice" buried in the middle. Someone typing the start of a word
    means the start of a word. */
export function prefixMatches(query: string, limit = 6): string[] {
  const q = query.trim().toLowerCase();
  if (q.length < 2) return [];

  const starts: string[] = [];
  const wordStarts: string[] = [];

  for (const name of FOOD_NAMES) {
    if (name.startsWith(q)) {
      starts.push(name);
      continue;
    }
    /* also match the start of any LATER word, so "chick" finds "grilled
       chicken" — people don't always begin with the first word of a dish */
    if (name.split(" ").slice(1).some((w) => w.startsWith(q))) {
      wordStarts.push(name);
    }
  }

  /* names that START with the query rank above ones that merely contain a
     matching word — "ric" should offer "rice" before "fried rice" */
  return [...starts, ...wordStarts].slice(0, limit);
}
